/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FractalPackage;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Yoan Hadad
 */
public class FractalWindow extends javax.swing.JFrame {

    /**
     * Creates new form FractalWindow
     */
    public FractalWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupThemes = new javax.swing.ButtonGroup();
        tbpnFractal = new javax.swing.JTabbedPane();
        pnlDrawStartup = new javax.swing.JPanel();
        btnMandelbrotSet = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        pnlDraw = new javax.swing.JPanel();
        lblZoom = new javax.swing.JLabel();
        pnlMandelbrotSettings = new javax.swing.JPanel();
        lblIterations = new javax.swing.JLabel();
        sldIterations = new javax.swing.JSlider();
        lblRedColor = new javax.swing.JLabel();
        lblBlueColor = new javax.swing.JLabel();
        lblGreenColor = new javax.swing.JLabel();
        sldRedColor = new javax.swing.JSlider();
        sldGreenColor = new javax.swing.JSlider();
        sldBlueColor = new javax.swing.JSlider();
        btnStartAnimation = new javax.swing.JButton();
        pnlBackgroundSettings = new javax.swing.JPanel();
        sldGreenBackground = new javax.swing.JSlider();
        lblRedBackground = new javax.swing.JLabel();
        lblGreenBackground = new javax.swing.JLabel();
        sldBlueBackground = new javax.swing.JSlider();
        sldRedBackground = new javax.swing.JSlider();
        lblBlueBackground2 = new javax.swing.JLabel();
        btnResetBackground = new javax.swing.JButton();
        btnSetBackground1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbpnFractal.setForeground(new java.awt.Color(51, 51, 51));
        tbpnFractal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnMandelbrotSet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMandelbrotSet.setText("Mandelbrot Set");
        btnMandelbrotSet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMandelbrotSetActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        pnlDraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDrawMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlDrawLayout = new javax.swing.GroupLayout(pnlDraw);
        pnlDraw.setLayout(pnlDrawLayout);
        pnlDrawLayout.setHorizontalGroup(
            pnlDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );
        pnlDrawLayout.setVerticalGroup(
            pnlDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        lblZoom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblZoom.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout pnlDrawStartupLayout = new javax.swing.GroupLayout(pnlDrawStartup);
        pnlDrawStartup.setLayout(pnlDrawStartupLayout);
        pnlDrawStartupLayout.setHorizontalGroup(
            pnlDrawStartupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDrawStartupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDrawStartupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlDrawStartupLayout.createSequentialGroup()
                        .addComponent(btnMandelbrotSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblZoom)))
                .addContainerGap())
        );
        pnlDrawStartupLayout.setVerticalGroup(
            pnlDrawStartupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDrawStartupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDrawStartupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDrawStartupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblZoom, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMandelbrotSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpnFractal.addTab("Drawing", pnlDrawStartup);

        lblIterations.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIterations.setForeground(new java.awt.Color(51, 51, 51));
        lblIterations.setText("Iterations:");

        sldIterations.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sldIterations.setForeground(new java.awt.Color(51, 51, 51));
        sldIterations.setMajorTickSpacing(100);
        sldIterations.setMaximum(1000);
        sldIterations.setPaintLabels(true);
        sldIterations.setPaintTicks(true);

        lblRedColor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRedColor.setForeground(new java.awt.Color(255, 0, 0));
        lblRedColor.setText("Red:");

        lblBlueColor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBlueColor.setForeground(new java.awt.Color(0, 153, 255));
        lblBlueColor.setText("Blue:");

        lblGreenColor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGreenColor.setForeground(new java.awt.Color(51, 153, 0));
        lblGreenColor.setText("Green:");

        sldRedColor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sldRedColor.setForeground(new java.awt.Color(51, 51, 51));
        sldRedColor.setMajorTickSpacing(32);
        sldRedColor.setMaximum(256);
        sldRedColor.setPaintLabels(true);
        sldRedColor.setPaintTicks(true);
        sldRedColor.setValue(256);

        sldGreenColor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sldGreenColor.setForeground(new java.awt.Color(51, 51, 51));
        sldGreenColor.setMajorTickSpacing(32);
        sldGreenColor.setMaximum(256);
        sldGreenColor.setPaintLabels(true);
        sldGreenColor.setPaintTicks(true);
        sldGreenColor.setValue(0);

        sldBlueColor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sldBlueColor.setForeground(new java.awt.Color(51, 51, 51));
        sldBlueColor.setMajorTickSpacing(32);
        sldBlueColor.setMaximum(256);
        sldBlueColor.setPaintLabels(true);
        sldBlueColor.setPaintTicks(true);
        sldBlueColor.setValue(165);

        btnStartAnimation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnStartAnimation.setText("Start Animation");
        btnStartAnimation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartAnimationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMandelbrotSettingsLayout = new javax.swing.GroupLayout(pnlMandelbrotSettings);
        pnlMandelbrotSettings.setLayout(pnlMandelbrotSettingsLayout);
        pnlMandelbrotSettingsLayout.setHorizontalGroup(
            pnlMandelbrotSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMandelbrotSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMandelbrotSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStartAnimation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMandelbrotSettingsLayout.createSequentialGroup()
                        .addComponent(lblIterations)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldIterations, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE))
                    .addGroup(pnlMandelbrotSettingsLayout.createSequentialGroup()
                        .addGroup(pnlMandelbrotSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRedColor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBlueColor)
                            .addComponent(lblGreenColor))
                        .addGap(12, 12, 12)
                        .addGroup(pnlMandelbrotSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sldRedColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sldGreenColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sldBlueColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlMandelbrotSettingsLayout.setVerticalGroup(
            pnlMandelbrotSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMandelbrotSettingsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlMandelbrotSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sldIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIterations))
                .addGap(12, 12, 12)
                .addGroup(pnlMandelbrotSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRedColor)
                    .addComponent(sldRedColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(pnlMandelbrotSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGreenColor)
                    .addComponent(sldGreenColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(pnlMandelbrotSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBlueColor)
                    .addComponent(sldBlueColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnStartAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        tbpnFractal.addTab("Mandelbrot Settings", pnlMandelbrotSettings);

        sldGreenBackground.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sldGreenBackground.setForeground(new java.awt.Color(51, 51, 51));
        sldGreenBackground.setMajorTickSpacing(51);
        sldGreenBackground.setMaximum(255);
        sldGreenBackground.setPaintLabels(true);
        sldGreenBackground.setPaintTicks(true);
        sldGreenBackground.setValue(217);

        lblRedBackground.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRedBackground.setForeground(new java.awt.Color(255, 0, 0));
        lblRedBackground.setText("Red:");

        lblGreenBackground.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGreenBackground.setForeground(new java.awt.Color(51, 153, 0));
        lblGreenBackground.setText("Green:");

        sldBlueBackground.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sldBlueBackground.setForeground(new java.awt.Color(51, 51, 51));
        sldBlueBackground.setMajorTickSpacing(51);
        sldBlueBackground.setMaximum(255);
        sldBlueBackground.setPaintLabels(true);
        sldBlueBackground.setPaintTicks(true);
        sldBlueBackground.setValue(223);

        sldRedBackground.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sldRedBackground.setForeground(new java.awt.Color(51, 51, 51));
        sldRedBackground.setMajorTickSpacing(51);
        sldRedBackground.setMaximum(255);
        sldRedBackground.setPaintLabels(true);
        sldRedBackground.setPaintTicks(true);
        sldRedBackground.setValue(214);

        lblBlueBackground2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBlueBackground2.setForeground(new java.awt.Color(0, 153, 255));
        lblBlueBackground2.setText("Blue:");

        btnResetBackground.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnResetBackground.setForeground(new java.awt.Color(255, 0, 0));
        btnResetBackground.setText("Reset Background");
        btnResetBackground.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetBackgroundActionPerformed(evt);
            }
        });

        btnSetBackground1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSetBackground1.setForeground(new java.awt.Color(0, 153, 0));
        btnSetBackground1.setText("Set Background");
        btnSetBackground1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetBackground1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundSettingsLayout = new javax.swing.GroupLayout(pnlBackgroundSettings);
        pnlBackgroundSettings.setLayout(pnlBackgroundSettingsLayout);
        pnlBackgroundSettingsLayout.setHorizontalGroup(
            pnlBackgroundSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundSettingsLayout.createSequentialGroup()
                        .addComponent(btnResetBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                        .addComponent(btnSetBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBackgroundSettingsLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBlueBackground2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRedBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGreenBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlBackgroundSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sldBlueBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                            .addComponent(sldGreenBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sldRedBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlBackgroundSettingsLayout.setVerticalGroup(
            pnlBackgroundSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundSettingsLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlBackgroundSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sldRedBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRedBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61)
                .addGroup(pnlBackgroundSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sldGreenBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGreenBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(pnlBackgroundSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBlueBackground2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sldBlueBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(pnlBackgroundSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSetBackground1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );

        tbpnFractal.addTab("Background", pnlBackgroundSettings);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpnFractal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpnFractal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //спира изпълнине на кода
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnMandelbrotSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMandelbrotSetActionPerformed
       //reset-ват се стойности на променливите нужни за увеличаване
       MandelbrotSetIsPresent=true;
       MandelbrotSet.copyMouseX=0;
       MandelbrotSet.copyMouseY=0;
       lblZoom.setVisible(false);
       
       mouseX=pnlDraw.getWidth()/2;
       mouseY=pnlDraw.getHeight()/2;
       
       //взима се избрания цвят
       int RGB[]=new int[3];
       RGB[0]=sldRedColor.getValue();
       RGB[1]=sldGreenColor.getValue();
       RGB[2]=sldBlueColor.getValue();
       
       zoom=1;
       //създава се обект от класа на фрактала
       int MaxIterations=sldIterations.getValue();
       mandel=new MandelbrotSet(pnlDraw.getWidth(),pnlDraw.getHeight(), MaxIterations, RGB, mouseX, mouseY, zoom);
       Graphics g=pnlDraw.getGraphics();
       
       //фрактала се рисува
       mandel.setSize(pnlDraw.getSize());
       pnlDraw.removeAll();
       pnlDraw.add(mandel);
       pnlDraw.repaint();
       Color customcolor = new Color(sldRedBackground.getValue(), sldGreenBackground.getValue(), sldBlueBackground.getValue());
       mandel.setBackground(customcolor);
       mandel.setOpaque(true);
    }//GEN-LAST:event_btnMandelbrotSetActionPerformed

    private void btnSetBackground1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetBackground1ActionPerformed
        //взима се избрания цвят
        Color customcolor = new Color(sldRedBackground.getValue(), sldGreenBackground.getValue(), sldBlueBackground.getValue());
        //прилага се на всички панели
        pnlBackgroundSettings.setBackground(customcolor);
        pnlDraw.setBackground(customcolor);
        pnlDrawStartup.setBackground(customcolor);
        pnlMandelbrotSettings.setBackground(customcolor);
        
        //проверка дали панела на фрактала съществува
        try{
            mandel.setBackground(customcolor);
        }catch(Exception e){
            System.out.println("Mandelbrot fractal not defined");
        }
        
    }//GEN-LAST:event_btnSetBackground1ActionPerformed

    private void btnResetBackgroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetBackgroundActionPerformed
        //слага се обичайния цвят
        Color customcolor = new Color(214, 217, 223);
        //прилага се на всички панели
        pnlBackgroundSettings.setBackground(customcolor);
        pnlDraw.setBackground(customcolor);
        pnlDrawStartup.setBackground(customcolor);
        pnlMandelbrotSettings.setBackground(customcolor);
        sldRedBackground.setValue(214);
        sldGreenBackground.setValue(217);
        sldBlueBackground.setValue(223);
        
        //проверка дали панела на фрактала съществува
        try{
            mandel.setBackground(customcolor);
        }catch(Exception e){
            System.out.println("Mandelbrot fractal not defined");
        }
    }//GEN-LAST:event_btnResetBackgroundActionPerformed

    private void btnStartAnimationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartAnimationActionPerformed
        //reset-ват се стойности на променливите нужни за увеличаване
        zoom=1;
        MandelbrotSetIsPresent=false;
        tbpnFractal.setSelectedIndex(0);
        //взиа се цвета на фрактала
        int RGB[] = new int[3];
        RGB[0] = sldRedColor.getValue();
        RGB[1] = sldGreenColor.getValue();
        RGB[2] = sldBlueColor.getValue();
        Color customColor = new Color(sldRedBackground.getValue(), sldGreenBackground.getValue(), sldBlueBackground.getValue());
        //взима се броя на кадрите при анимацията
        int maxIterations = sldIterations.getValue();
        //създава се таймер с 0.05 сек между отделните кадри 
    Timer mandelbrotTimer = new Timer(50, new ActionListener() {
        
        int i = 0; //брояч на повторения
        
        
        @Override
        public void actionPerformed(ActionEvent e) {
            //проверка за край на анимацията
            if (i >= maxIterations) {
                ((Timer) e.getSource()).stop();
                String message="Drawing complete!";
                JOptionPane.showMessageDialog(null, message);
                return;
            }
            //създава се фрактал с дълбочина i
            MandelbrotSet mandel = new MandelbrotSet(pnlDraw.getWidth(), pnlDraw.getHeight(), i, RGB, pnlDraw.getWidth()/2, pnlDraw.getHeight()/2, 1);
            MandelbrotSet.copyMouseX=0;
            MandelbrotSet.copyMouseY=0;
            //фракталът се рисува
            mandel.setSize(pnlDraw.getSize());
            mandel.setBackground(customColor);
            mandel.setOpaque(true);
            pnlDraw.removeAll();
            pnlDraw.add(mandel);
            pnlDraw.repaint();
            
            i++;
        }
    });
    //стартиране на таймер
    mandelbrotTimer.start(); 
    }//GEN-LAST:event_btnStartAnimationActionPerformed

    private void pnlDrawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDrawMouseClicked

        //проверка за наличието на фрактала, ако е наличе кодът се изпълнява
        if (MandelbrotSetIsPresent){
            //взимат се координати на мишката, увелечава се приближението и се взима цвят
            
            mouseX=evt.getX();
            mouseY=evt.getY();
            
            
            zoom*=2;
            lblZoom.setText("zoom: x"+zoom);
            lblZoom.setVisible(true);
            
            int RGB[]=new int[3];
            RGB[0]=sldRedColor.getValue();
            RGB[1]=sldGreenColor.getValue();
            RGB[2]=sldBlueColor.getValue();
       
            int MaxIterations=sldIterations.getValue();
            
            mandel=new MandelbrotSet(pnlDraw.getWidth(),pnlDraw.getHeight(), MaxIterations, RGB, mouseX, mouseY, zoom);
            
            Graphics g=pnlDraw.getGraphics();
      
       
            mandel.setSize(pnlDraw.getSize());
            pnlDraw.removeAll();
            pnlDraw.add(mandel);
            pnlDraw.repaint();
            Color customcolor = new Color(sldRedBackground.getValue(), sldGreenBackground.getValue(), sldBlueBackground.getValue());
            mandel.setBackground(customcolor);
            mandel.setOpaque(true);
        }
    }//GEN-LAST:event_pnlDrawMouseClicked
    

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FractalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FractalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FractalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FractalWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FractalWindow().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnMandelbrotSet;
    private javax.swing.JButton btnResetBackground;
    private javax.swing.JButton btnSetBackground1;
    private javax.swing.JButton btnStartAnimation;
    private javax.swing.ButtonGroup btngroupThemes;
    private javax.swing.JLabel lblBlueBackground2;
    private javax.swing.JLabel lblBlueColor;
    private javax.swing.JLabel lblGreenBackground;
    private javax.swing.JLabel lblGreenColor;
    private javax.swing.JLabel lblIterations;
    private javax.swing.JLabel lblRedBackground;
    private javax.swing.JLabel lblRedColor;
    private javax.swing.JLabel lblZoom;
    private javax.swing.JPanel pnlBackgroundSettings;
    private javax.swing.JPanel pnlDraw;
    private javax.swing.JPanel pnlDrawStartup;
    private javax.swing.JPanel pnlMandelbrotSettings;
    private javax.swing.JSlider sldBlueBackground;
    private javax.swing.JSlider sldBlueColor;
    private javax.swing.JSlider sldGreenBackground;
    private javax.swing.JSlider sldGreenColor;
    private javax.swing.JSlider sldIterations;
    private javax.swing.JSlider sldRedBackground;
    private javax.swing.JSlider sldRedColor;
    private javax.swing.JTabbedPane tbpnFractal;
    // End of variables declaration//GEN-END:variables

MandelbrotSet mandel;
int zoom=1;
boolean MandelbrotSetIsPresent=false;
int mouseX=0;
int mouseY=0;
}
